### ISSUE TITLE
[BUG] ha-cluster for resource manager does not work

### ISSUE THREAD

**Issue by pycgo** [prestodb/presto-helm-charts#1]
#### Steps to reproduce:

I have 5 worker nodes. When there is only one resource manager, everything is normal. When there are 2 resource managers, the active workers on the web ui randomly change between 0 and 5.

resource manager many log like this:
2023-09-12T08:37:25.879Z        INFO    node-state-poller-0     com.facebook.presto.metadata.DiscoveryNodeManager       Previously active node is missing: f6f5f500-c887-44d3-9104-e24fe5767c4b (last seen at 10.88.29.215)

## Additional context

![image](https://github.com/prestodb/presto-helm-charts/assets/55949132/d7611c87-24e3-4d7b-9970-8fe8e29d130a)

**Comment by piyu5h** [comment]
Hi @pycgo  Did you find any solution for this behaviour? 
We are also facing same.

**Comment by pycgo** [comment]
> Hi @pycgo Did you find any solution for this behaviour? We are also facing same.

no...

**Comment by dnskr** [comment]
It seems to be a misconfiguration issue rather than a bug.

As far as I know, Resource Manager pool follows active/standby approach, so only one RM instance should play the leader role. It can be configured on a load balancer level in non-Kubernetes environments, but not in pure Kubernetes without unreliable tricks or third-party sidecar containers.

However, I found that Presto has Ratis Server which can be used to solve leader election problem: https://github.com/prestodb/presto/pull/17853
It's not configured in Presto by default and requires few additional jars to be added to `lib` folder:

- ratis-common-2.2.0.jar
- ratis-server-api-2.2.0.jar
- ratis-server-2.2.0.jar
- ratis-client-2.2.0.jar
- ratis-grpc-2.2.0.jar
- ratis-proto-2.2.0.jar
- ratis-thirdparty-misc-0.7.0.jar
- ratis-metrics-2.2.0.jar
- metrics-core-3.2.5.jar

I'll bring it up in Presto Slack and probably come back with a solution proposal.

**Comment by tdcmeehan** [comment]
I would recommend making the helm chart configuration for the resource manager to only include one replica of the resource manager.  The cluster will tolerate process bounce of the resource manager, and as long as Kubernetes brings up the replacement process quickly, then it won't affect the operation of the cluster.

**Comment by dnskr** [comment]
> I would recommend making the helm chart configuration for the resource manager to only include one replica of the resource manager. The cluster will tolerate process bounce of the resource manager, and as long as Kubernetes brings up the replacement process quickly, then it won't affect the operation of the cluster.

Thank you for explanation, sounds reasonable to me.

@pycgo Resource Manager replica count has been made immutable and equal to 1 as recommended in the comment above. The change will be available in the next release. In the current release, please keep 1 in `resourceManager.replicas` value.
Would it make sense if we close the issue?

**Comment by pycgo** [comment]
Perhaps my understanding is incorrect. I wanted to see the implementation of this multi coordinator, rather than relying on k8s for external load balancing. This is not what I wanted
If the value is set to 1, the work of this link seems meaningless and cannot be directly deployed for production[https://prestodb.io/blog/2022/04/15/disggregated-coordinator/](url)

**Comment by dnskr** [comment]
@pycgo Right, it might be not so clear and a bit confusing, so let me explain.

Main purpose of [Disaggregated Coordinator](https://prestodb.io/blog/2022/04/15/disggregated-coordinator/) is to horizontally scale coordinators across a common pool of workers, because single coordinator is a single point of failure and bottleneck in clusters with multiple complex queries. Resource Manager availability is not so critical in Disaggregated Coordinator setup as @tdcmeehan explained in the comment above, i.e. it's fine to have only one RM replica in a cluster. Actually to configure Disaggregated Coordinator with the Helm chart, it's enough to use the following properties:
```yaml
mode: ha-cluster
coordinator:
  replicas: 2
worker:
  replicas: 2
```

**Comment by pycgo** [comment]
> @pycgo Right, it might be not so clear and a bit confusing, so let me explain.
> 
> Main purpose of [Disaggregated Coordinator](https://prestodb.io/blog/2022/04/15/disggregated-coordinator/) is to horizontally scale coordinators across a common pool of workers, because single coordinator is a single point of failure and bottleneck in clusters with multiple complex queries. Resource Manager availability is not so critical in Disaggregated Coordinator setup as @tdcmeehan explained in the comment above, i.e. it's fine to have only one RM replica in a cluster. Actually to configure Disaggregated Coordinator with the Helm chart, it's enough to use the following properties:
> 
> ```yaml
> mode: ha-cluster
> coordinator:
>   replicas: 2
> worker:
>   replicas: 2
> ```

OK got it
